### ISSUE TITLE
Authentication failed for https://api.smith.langchain.com/runs. HTTPError('401 Client Error: Unau...

### ISSUE THREAD

**Issue by fabiolatagne97** [mongulu-cm/tchoung-te#157]
You can find the issue details here: https://mongulu.sentry.io/issues/6088787149/?referrer=webhooks_plugin

**Comment by fabiolatagne97** [comment]
@fabiolatagne97 l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by billmetangmo** [comment]
Fixed the issue the langchain crednetails was external-secrets based and i did not chnaged there, I update an dit works like a charm.
