### ISSUE TITLE
Create a chat app like chatgpt to allow search in the database v1

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/tchoung-te#63]
Multiples ways of solving:

- Use https://github.com/jerryjliu/gpt_index & https://github.com/hwchase17/langchain ( example https://github.com/arc53/DocsGPT ) . Pour le chargement utilisez un loader https://llamahub.ai/l/file-simple_csv ?
- Supabase Clippy: ChatGPT for Supabase Docs: https://supabase.com/blog/chatgpt-supabase-docs
- Use aista https://aista.hashnode.dev/open-source-chatgpt-based-bing-search-launched
- Use haystack https://github.com/deepset-ai/haystack
- Use Hugging face https://github.com/huggingface/transformers ?
- API de chatgpt ( released on March 2th https://platform.openai.com/docs/guides/chat )
-  The smallest possible LLM API : https://github.com/tomdyson/microllama
- OpenAI ChatGPT plugin: https://github.com/openai/chatgpt-retrieval-plugin
- Llama : https://github.com/ggerganov/llama.cpp

**Comment by billmetangmo** [comment]
Create a simple data app for the first version using streamlit

**Comment by billmetangmo** [comment]
https://www.youtube.com/watch?v=XgD5AuzBvs8

**Comment by billmetangmo** [comment]
Search using the relevant documents provided by semantic search: may be we can use embedding then search using OpenAI ? https://learnprompting.org/docs/applied_prompting/build_chatbot_from_kb ?

**Comment by KameniAlexNea** [comment]
Here's a formatted explanation of the traceback for other developers:

```plaintext
Traceback (most recent call last):
  File "/home/eak/Documents/AI/DeepLearning/tchoung-te/.venv/bin/chainlit", line 8, in <module>
    sys.exit(cli())
  ...
  ...
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for StuffDocumentsChain
__root__
  document_variable_name summaries was not found in llm_chain input_variables: ['context', 'question'] (type=value_error)

This is the part of the code that failed:

llm = ChatOpenAI(max_tokens=500, temperature=0, model_name="gpt-3.5-turbo")
chain_type_kwargs = {"prompt": CHAT_PROMPT}
qa = RetrievalQAWithSourcesChain.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectors.as_retriever(search_kwargs={"k": 3}),
    chain_type_kwargs=chain_type_kwargs,
    return_source_documents=True
)
```

The traceback indicates an error in the code, specifically in the part where you're initializing the `qa` object. The error message (`pydantic.error_wrappers.ValidationError`) suggests that there's a validation error related to the `StuffDocumentsChain` and its input variables. The error message details that the variable name `summaries` was not found in the `llm_chain input_variables`. You might need to check the input variables and ensure that `summaries` is properly defined or used in your code.

**Comment by KameniAlexNea** [comment]
@billmetangmo  Done on our side (@Joyce-Tchamdjou )

**Comment by billmetangmo** [comment]
One output key expected, got dict_keys(['result', 'source_documents'])
