### ISSUE TITLE
Réfléchier à la possibilité de faire que le chargement pandas soit plus rapide 

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/tchoung-te#70]
S'aider de https://www.manning.com/books/fast-python?trk_msg=IFUPDJLABII4R5OVI6G8R4QCCO&trk_contact=DFQVG868N8R8DDR5K4JB3U354G&trk_sid=M1MICTHGK003IJJ9JR5NA4HQ60&trk_link=P5R4N8JIPKU4781B0JENSJ855O&utm_source=Listrak&utm_medium=Email&utm_term=https%3a%2f%2fwww.manning.com%2fbooks%2ffast-python&utm_campaign=Two+together!+Buy+one%2c+get+one+free+this+Valentine%e2%80%99s+Day en le checkant sur zlib

**Comment by billmetangmo** [comment]
- Lire que les données qui t'intéresse , utiliser pickle.

**Comment by CyriacAzefack** [comment]
On a diviser par 2 le temps de chargement des fichiers CSV.
